import os
import sys
import json
import datetime
from pathlib import Path

REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)


def collect_context():
    security_text = ""
    for fname in ["trivy-report.txt", "reports/trivy-report.txt"]:
        p = Path(fname)
        if p.exists():
            content = p.read_text()
            security_text = content[:1500] + ("..." if len(content) > 1500 else "")
            break

    def status_icon(s):
        return {"success": "✅", "failure": "❌", "skipped": "⏭️"}.get(s, "❓")

    build_s  = os.getenv("STATUS_BUILD",  "unknown")
    scan_s   = os.getenv("STATUS_SCAN",   "unknown")
    push_s   = os.getenv("STATUS_PUSH",   "unknown")
    deploy_s = os.getenv("STATUS_DEPLOY", "unknown")

    return {
        "pipeline": {
            "repo":      os.getenv("REPO",      "unknown"),
            "branch":    os.getenv("BRANCH",    "unknown"),
            "sha":       os.getenv("SHORT_SHA", "unknown"),
            "actor":     os.getenv("ACTOR",     "unknown"),
            "timestamp": datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        },
        "jobs": {
            "build":  f"{status_icon(build_s)}  {build_s.upper()}",
            "scan":   f"{status_icon(scan_s)}   {scan_s.upper()}",
            "push":   f"{status_icon(push_s)}   {push_s.upper()}",
            "deploy": f"{status_icon(deploy_s)} {deploy_s.upper()}",
        },
        "image": {
            "ecr_uri": os.getenv("ECR_URI", "not-pushed"),
        },
        "changes": {
            "commits":       os.getenv("COMMIT_MSGS",   "no commits"),
            "files_changed": os.getenv("CHANGED_FILES", "no files"),
        },
        "security": security_text or "No Trivy report found.",
    }


def build_summary_prompt(ctx):
    all_success = all("SUCCESS" in v for v in ctx["jobs"].values())
    overall = "SUCCESS" if all_success else "FAILED"
    return f"""You are a senior DevOps engineer writing deployment documentation.
Analyze this CI/CD pipeline execution and write a structured Markdown deployment summary.

## Pipeline Data
```json
{json.dumps(ctx, indent=2)}
```

Write professional Markdown with these sections:

# Deployment Summary — {overall}

## Executive Summary
2-3 sentence high-level outcome.

## Pipeline Status
A Markdown table: Job | Status | Notes

## Image Details
ECR URI, short SHA, timestamp.

## Security Assessment
Brief summary of Trivy findings. Call out CRITICAL/HIGH if present.

## Changes Deployed
Plain-English summary of the commits and files changed.

## Recommendations
2-3 concrete actionable suggestions.

Output ONLY the Markdown, no preamble."""


def build_release_notes_prompt(ctx):
    return f"""You are a technical writer generating release notes.

## Recent commits
{ctx['changes']['commits']}

## Changed files
{ctx['changes']['files_changed']}

## Image
{ctx['image']['ecr_uri']}

## Timestamp
{ctx['pipeline']['timestamp']}

Write clean Markdown release notes with these sections:
- What's new
- Bug fixes (omit if none)
- Infrastructure/CI changes
- Breaking changes (write "None" if none)
- Deployment metadata (image URI, SHA, timestamp)

Output ONLY the Markdown, no preamble."""


def call_gemini(api_key, prompt, label):
    import google.generativeai as genai
    print(f"Calling Gemini for: {label}")
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-1.5-flash")
    try:
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.3,
                max_output_tokens=1500,
            ),
        )
        print(f"  Done: {label} ({len(response.text)} chars)")
        return response.text
    except Exception as e:
        print(f"  Error: {e}", file=sys.stderr)
        return f"## AI generation failed\n\nError: `{e}`\n"


def write_header(ctx):
    all_success = all("SUCCESS" in v for v in ctx["jobs"].values())
    badge = "ALL JOBS PASSED" if all_success else "PIPELINE FAILED"
    return f"""# AI Deployment Report — {badge}

> Generated by Google Gemini 1.5 Flash (FREE) | {ctx['pipeline']['timestamp']}
> Repo: `{ctx['pipeline']['repo']}` · Branch: `{ctx['pipeline']['branch']}` · SHA: `{ctx['pipeline']['sha']}`

| Job | Status |
|-----|--------|
| Docker Build | {ctx['jobs']['build']} |
| Security Scan | {ctx['jobs']['scan']} |
| Push to ECR | {ctx['jobs']['push']} |
| Deploy to EC2 | {ctx['jobs']['deploy']} |

---

"""


def main():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("GEMINI_API_KEY not set — writing fallback report.", file=sys.stderr)
        fallback = (
            "## AI Summary Unavailable\n\n"
            "Add `GEMINI_API_KEY` to your GitHub Secrets.\n"
            "Get a free key at: https://aistudio.google.com/app/apikey\n"
        )
        (REPORTS_DIR / "ai-summary.md").write_text(fallback)
        (REPORTS_DIR / "release-notes.md").write_text(fallback)
        sys.exit(0)

    ctx = collect_context()
    print(f"Repo:   {ctx['pipeline']['repo']}")
    print(f"Branch: {ctx['pipeline']['branch']}")
    print(f"SHA:    {ctx['pipeline']['sha']}")

    header       = write_header(ctx)
    summary_body = call_gemini(api_key, build_summary_prompt(ctx),       "Deployment Summary")
    release_body = call_gemini(api_key, build_release_notes_prompt(ctx), "Release Notes")

    (REPORTS_DIR / "ai-summary.md").write_text(header + summary_body)
    (REPORTS_DIR / "release-notes.md").write_text(
        f"# Release Notes\n\n"
        f"> SHA `{ctx['pipeline']['sha']}` · {ctx['pipeline']['timestamp']}\n\n"
        + release_body
    )

    print("Reports written to reports/ai-summary.md and reports/release-notes.md")


if __name__ == "__main__":
    main()
